# Generated by Django 5.0.4 on 2024-04-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineLearning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='data',
            field=models.FileField(default=None, upload_to='media/tmp', verbose_name='Данные'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='forecast',
            field=models.JSONField(blank=True, null=True, verbose_name='Предсказания'),
        ),
    ]
