# Generated by Django 5.0.4 on 2024-04-14 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machineLearning', '0003_alter_dashboard_options_dashboard_adfuler_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='cointegration_test',
        ),
    ]
