# Generated by Django 5.0.4 on 2024-04-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userphoto_photo_alter_userphoto_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='photo',
            field=models.ImageField(null=True, upload_to='avatar/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
