# Generated by Django 5.0.4 on 2024-04-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_userphoto_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dota_mmr',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dota_pos',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tanks_rating',
        ),
        migrations.RemoveField(
            model_name='user',
            name='who_are_you',
        ),
        migrations.DeleteModel(
            name='UserPhoto',
        ),
    ]
